checkout/checkout-sdk-go

- payments/payment.go
Co-authored-by: ShiuhYaw <shiuhyaw.phang@checkout.com>
On branch INT-148
Changes to be committed:
modified:   payments/payment.go
> INT-148: add merchant_inititated variable to payment request

- .github/PULL_REQUEST_TEMPLATE.md
- .github/settings.yml
- checkout.go
- client/api.go
- files/file.go
- httpclient/client.go
- internal/utils/utils.go
- reconciliation/client.go
This Pull Request introduces 
- `internal` packages
- Pull request template
More about internal packages:
https://dave.cheney.net/2019/10/06/use-internal-packages-to-reduce-your-public-api-surface
> Refactor checkout.go and introduce internal package

- common/common.go
- configuration/oauth_scopes.go
- metadata/client.go
- metadata/client_test.go
- metadata/metadata.go
- metadata/sources/sources.go
- nas/checkout_api.go
- test/disputes_test.go
- test/metadata_card_request_test.go
- test/sandbox_test_fixture_test.go
- test/tokens_test.go
Added support for card metadata (CS2)
https://api-reference.checkout.com/#tag/Card-metadata
> Added support for card metadata (CS2)

- accounts/client.go
Support Secret Key for Accounts (CS2)
> API Updates: Support Secret Key for Accounts (CS2)

- client/version.go
* Added support for `bank account` field formatting (CS2)
* Added support for `get payment lists` (CS1/CS2)
* Added support for `card metadata` (CS2)
* Adds support for `Workflows` (CS2)
* Adds support for `Hosted/Link Payments` (CS1/CS2)
* Adds support for `Dispute Scheme Files` API (CS1/CS2)
* Added support for `Logging` and Custom logger
* Added new Integrated Platforms payment instrument endpoints to `Accounts` (CS2)
* Added prism score property to payment response risk object
* Added `device_session_id` to RiskRequest
* Added mandatory fields for MIT/CIT payments sources (CS1/CS2)
* API Updates: Support Secret Key for `Accounts` (CS2)
> Release 1.0.0-beta.2

- balances/balances.go
- balances/client.go
- balances/client_test.go
- nas/checkout_api.go
- test/balances_test.go
- test/sandbox_test_fixture_test.go
- test/transfers_test.go
- transfers/client.go
- transfers/client_test.go
- transfers/transfers.go
Added support for Transfers & Balances (CS2)
https://api-reference.checkout.com/#operation/getEntityBalances
https://api-reference.checkout.com/#operation/createTransfer
https://api-reference.checkout.com/#operation/getTransferDetails
> Added support for Transfers & Balances (CS2)

- payments/abc/client_test.go
- payments/abc/payments.go
- payments/abc/sources/apm/apm.go
- payments/abc/sources/sources.go
- payments/nas/client_test.go
- payments/nas/payments.go
- payments/nas/sources/apm/apm.go
- payments/nas/sources/sources.go
- payments/payments.go
- payments/sources.go
- test/oauth_sdk_test.go
- test/payments_request_apm_previous_test.go
- test/payments_request_apm_test.go
- test/payments_request_previous_test.go
- test/payments_request_test.go
- tokens/tokens.go
* Refactor payments sources to implement PaymentSource interface
* Refactor tokens data to implement TokenData interface
> Review structs implementing interfaces{}

- client/version.go
* Refactors payout schemas to implement interfaces (CS1/CS2)
* Refactors payments sources to implement PaymentSource interfaces (CS1/CS2)
* Refactors tokens data to implement TokenData interface (CS1/CS2)
* Changes amount related fields type from int to int64
> Release 1.0.1

- abc/checkout_api.go
- test/sources_test.go
- test/transfers_test.go
- test/webhooks_test.go
- transfers/client_test.go
- transfers/transfers.go
- webhooks/abc/client.go
- webhooks/abc/client_test.go
- webhooks/abc/webhooks.go
Adding support for Webhooks CS1
https://api-reference.checkout.com/previous/#tag/Webhooks
> Adding support for Webhooks CS1

- client/version.go
* Add support for Events (CS1)
* Add support for Webhooks (CS1)
* Add support for Reconciliations (CS1)
* Update Sepa URL for PPro actions (CS1)
* Review payment & payout request schemas (CS1/CS2)
> Release 1.0.2

- payments/nas/sources/apm/apm.go
- payments/payments.go
- test/events_test.go
- test/payments_request_apm_test.go
[Add properties for payment.processing response by yelena-pakumirzakova-cko · Pull Request #820 · checkout/checkout-api-reference](https://github.com/checkout/checkout-api-reference/pull/820) 
[Add SEPAV4 sources by andre-lopes-cko · Pull Request #829 · checkout/checkout-api-reference](https://github.com/checkout/checkout-api-reference/pull/829)
> API updates

- test/instruments_previous_test.go
- test/instruments_test.go
- test/payments_actions_previous_test.go
- test/payments_actions_test.go
- test/payments_captures_previous_test.go
- test/payments_captures_test.go
- test/payments_payouts_previous_test.go
- test/payments_refunds_previous_test.go
- test/payments_refunds_test.go
- test/payments_request_previous_test.go
- test/payments_request_test.go
- test/payments_voids_previous_test.go
- test/payments_voids_test.go
Refactor old tests to match current format
> Refactor old tests to match current format

- client/version.go
- Added API key auth to Integrated Platforms Balances (CS2)
- Added patch endpoint for payment instruments (CS2)
- Replace ‘reporting’ scopes with 'reports' on the Reports API (CS2)
- Add new CvConnect APM (CS2)
- Add new Illicado APM (CS2)
- Add new Trustly APM (CS2)
- Rename partner_reason field to partner_error_message in Payments ProcessingData (CS2)
- Refactor old tests to match current format
- Adds support for Financial Actions API
- Add properties for payment.processing response
- Add SEPAV4 sources
- Fix installation instructions
- Fixes Accounts test suite
> Release 1.0.3

- client/version.go
* Updates GiroPay request object (CS2)
* Adds new sections for adding/deleting workflow actions and workflow conditions (CS2)
* Adds ‘Unscheduled‘ payment_type to payment request (CS1/CS2)
* Removes ‘to‘ and ‘from‘ fields from Notifications > Events (CS1)
> Release 1.0.4

- client/version.go
- Added missing Sessions Fields (CS2)
> Release 1.0.5

- client/version.go
* Add javascript_enabled field in ChannelData for request session and update session (browser channel)
* Add reference property to Financial Actions query
* Add support for Forex (FX) rates API
* Remove marketplace from HostedPayments & PaymentLinks
> Release 1.0.6

- client/version.go
* Fixes `GooglePayTokenData` signature field name
* Adds `card_token` object to `PaymentInstrumentRequest` for Integrated Platforms (CS2)
* Adds `if-match` header to `UpdatePaymentInstrumentRequest` for Integrated Platforms (CS2)
* Fixes typo for `TransactionCurrencyAmount` in Financial Actions (CS2)
#64 
#65
> Release 1.0.7

- client/version.go
* Converts all time.Time fields to pointers
> Release 1.0.8

- client/version.go
- Added missing and properties in Customers Instruments
- Updates conflict response for onboard sub entity operation to include ID
- Added property authentication_status_reason to 3DS object in the GET payment details response
> Release 1.0.9

- test/accounts_test.go
- test/customers_previous_test.go
- test/customers_test.go
- test/events_test.go
- test/instruments_previous_test.go
- test/instruments_test.go
* Adds setup for `Accounts` integration tests suite (CS2)
* Adds setup for `Customers` integration tests suite (CS1)
* Adds setup for `Customers` integration tests suite (CS2)
* Adds setup for `Instruments` integration tests suite (CS1)
* Adds setup for `Instruments` integration tests suite (CS2)
> Improve Integration Tests Performance

- client/version.go
- Improve Integration Tests Performance
- Adds setup for Accounts integration tests suite (CS2)
- Adds setup for Customers integration tests suite (CS1)
- Adds setup for Customers integration tests suite (CS2)
- Adds setup for Instruments integration tests suite (CS1)
- Adds setup for Instruments integration tests suite (CS2)
- Fix json tags in metadata package
> Release 1.0.12

- client/version.go
- CodeQL workflow for Go
- Adds Increment Authorization Payments (CS2)
> Release 1.0.13

- payments/abc/client.go
- payments/nas/client.go
- test/payments_captures_previous_test.go
- test/payments_captures_test.go
- Update capture payment request param to optional
> Update capture payment request param

- client/version.go
- Update capture payment request param to optional
> Release 1.0.14

- client/version.go
- Add CurrencyAccountId to AccountBalance struct
> Release 1.0.15

- client/version.go
- test/payments_request_apm_test.go
- Add WithCurrencyAccountId to QueryFilter struct
> Release 1.0.16

- client/version.go
- test/payments_request_apm_test.go
- Remove omitempty tag from AmountAllocations's amount field (#96)
> Release 1.0.17

- .github/workflows/build-master.yml
- .github/workflows/build-pull-request.yml
- .github/workflows/build-release.yml
- configuration/oauth_scopes.go
- nas/checkout_api.go
- payments/contexts/client.go
- payments/contexts/client_test.go
- payments/contexts/contexts.go
- payments/nas/source.go
- payments/nas/sources/contexts/contexts.go
- payments/payments.go
- test/payment_context_test.go
- Adds request and get `payment contexts` endpoints
> Payment Contexts Support (CS2)

- client/version.go
- Adds request and get `payment contexts` endpoints
> Release 1.0.18

- payments/nas/payments.go
- payments/nas/source.go
- payments/nas/sources/apm/apm.go
- payments/payments.go
- test/payments_request_apm_test.go
- Update payment request for payment contexts
- Update giropay source
- Update properties and tests
> Update Payment Context And Properties

- client/version.go
- Adds `payment sessions` support
- Update `payment request` for `payment contexts`
- Update `giropay` source
- Update properties and tests
> Release 1.0.19

- accounts/common.go
- payments/contexts/contexts.go
- payments/sessions/client_test.go
- payments/sessions/sessions.go
- test/payment_sessions_test.go
- test/payments_request_apm_test.go
- Update onboard entity request
- Update payment contexts
- Update payment sessions response. Fix tests.
> Update onboard entity request, payment contexts

- client/version.go
- Adds subdomain for merchants
- Adds ChallengeNotificationUrl to nonHostedCompletion
- Adds compiled submitted evidence endpoint to disputes
- Adds documents to OnboardEntityRequest
- Update PaymentContextDetailsResponse
- Update onboard entity request
- Update payment contexts
- Update payment sessions response
- Update hosted payment request with disabled payment methods
- Fix tests
> Release 1.1.0

- accounts/common.go
- common/files.go
- metadata/metadata.go
- Update card metadata response properties
- Update purpose types
- Update profile class with holding currencies
> Properties update for Metadata, Purpose and Profile

- payments/contexts/client_test.go
- payments/contexts/contexts.go
- payments/nas/sources/contexts/contexts.go
- payments/sessions/client_test.go
- payments/sessions/sessions.go
- test/payment_context_test.go
- test/payment_sessions_test.go
- Update Payment Components
- Adds Klarna Payment Context Support
- Fix PayPal name files
> Update Payment Components. Klarna Payment Context Support

- common/common.go
- payments/nas/source.go
- payments/nas/sources/apm/apm.go
- sessions/sessions.go
- test/payments_captures_test.go
- test/payments_request_apm_test.go
- Ideal Payment Update (CS2)
- Card Wallet Type Support
- Sessions Authentication Type Update
> Ideal Payment Update (CS2). Card Wallet Type Support. Sessions Authentication Type Update

- client/version.go
- Adds SEPA Direct Debit Core Support
- Adds Klarna Payment Context Support
- Adds Card Wallet Type Support
- Update card metadata response properties
- Update purpose types
- Update profile class with holding currencies
- Update Payment Components
- Update Ideal Payment (CS2)
- Update Sessions Authentication Type
- Fix LocalSchemes property
- Fix Rates property
- Fix PayPal name files
> Release 1.2.0

- payments/sessions/sessions.go
- Fix payment methods flow type
> Fix payment methods flow type

- common/common.go
- common/serializer.go
- common/serializer_test.go
> Fix PDF download error

- payments/nas/payments.go
- payments/payments.go
- Update Payment Response with last properties
> Update Payment Response with last properties

- configuration/environment.go
- test/configuration_api_test.go
- Update length subdomain names validation
> Update length subdomain names validation

- client/version.go
- test/payments_request_apm_previous_test.go
- Adds destination object inside refund payment request
- Updates length subdomain names validation
- Updates Payment Response with last properties
- Fixes PDF download error
- Fixes payment methods flow type
> Release 1.2.1

- client/version.go
- Adds partial authorization in payment request
- Fixes account holder payment context source
> Release 1.2.2

- common/common.go
- sessions/channels/channels.go
- sessions/sessions.go
- sessions/sessions_requests.go
- sessions/sessions_responses.go
- sessions/sources/session_sources.go
- test/reports_test.go
- test/sessions_test.go
- workflows/client_test.go
- Update payment sessions schemas
> Update payment sessions schemas

- client/version.go
- Updates payment sessions schemas
> Release 1.2.3

- configuration/environment.go
- test/configuration_api_test.go
- Updates DNS Merchant regular expression length
> Update DNS Merchant regular expression length

- client/version.go
- Updates DNS Merchant regular expression length
> Release 1.2.4

- client/version.go
- test/payments_captures_test.go
- Updates Knet APM payment
- Updates Workflow properties and endpoints
> Release 1.2.5

- client/version.go
> Release 1.2.6

- common/common.go
- metadata/metadata.go
- payments/links/links.go
- Update Payment Link Request
- Update Card Metadata Response
> Update Payment Link Request. Update Card Metadata Response

- client/version.go
- Updates Payment Link Request
- Updates Card Metadata Response
> Release 1.2.7

- client/version.go
- Fixes cvc2
- Skips previous tests
> Release 1.3.1

- client/version.go
- Adds display_name Property to Hosted Payment Request
> Release 1.3.3

- client/version.go
- Adds new fields and update tests for payment processing
- Enhances with new account features
> Release 1.4.0

- accounts/accounts.go
- common/common.go
- payments/contexts/contexts.go
- payments/hosted/hosted.go
- payments/payments.go
- payments/sessions/sessions.go
- payments/sources.go
- test/customers_previous_test.go
- test/hosted_payments_previous_test.go
- test/hosted_payments_test.go
- test/payment_context_test.go
- test/payments_refunds_test.go
- Update Hosted Payment Page with latest changes
- Update Customer Requests implementations
- Enhance Accounts for Account holder implementations
- Update tests
> Update Hosted Payment Page Payment Contexts and tests

- client/version.go
- test/payment_context_test.go
- Updates Hosted Payment Page
- Updates Payment Contexts
- Updates Tests
> Release 1.5.0

- accounts/accounts.go
- accounts/client_test.go
- accounts/instruments.go
- common/common.go
- payments/destinations.go
- payments/nas/destinations.go
- payments/nas/payments.go
- payments/nas/senders.go
- payments/nas/source.go
- payments/nas/sources/apm/apm.go
- payments/nas/sources/sources.go
- payments/payments.go
- payments/sources.go
- sessions/sessions.go
- sessions/sessions_requests.go
- test/apm_ideal_test.go
- test/apm_klarna_test.go
- test/disputes_previous_test.go
- test/events_test.go
- test/payment_links_previous_test.go
- test/payments_voids_previous_test.go
- Update payments properties and refactor
> Update payments properties and refactor

- client/version.go
- Updates payments properties and refactor
- Allows Amount to be zero in sessions.PaymentSessionsRequest
- Adds resolved_reason mapping to dispute_summary
> Release 1.6.0

- client/version.go
- Updates Shipping and 3ds structs to be compatible with HPP and PL
> Release 1.6.1

- payments/hosted/hosted.go
- payments/links/links.go
- payments/payments.go
- payments/sessions/sessions.go
- test/hosted_payments_test.go
- test/payment_links_test.go
- test/payment_sessions_test.go
- Update Shipping and 3ds struct in Flow
> Update Shipping and 3ds struct in Flow

- client/version.go
- Updates Shipping and 3ds struct in Flow
> Release 1.6.2

- client/version.go
- Updates Processing with PartnerCustomerRiskData
> Release 1.6.3

- payments/payments.go
- Fix SurchargeAmount with omitempty
> Fix SurchargeAmount with omitempty

- common/common.go
- payments/nas/client_test.go
- payments/nas/source.go
- Add AccountHolderResponse and related types for account holder inquiries
> Add AccountHolderResponse and related types for account holder inquiries

- client/version.go
- Adds support to Forward Stored Credentials and some refactors and updates
- Adds AccountHolderResponse and related types for account holder inquiries
- Adds Currency field to TransferSourceRequest and update tests
> Release 1.7.0

- client/version.go
- Adds signature handling for dLocal API requests
> Release 1.7.1
